spring:
  application:
    name: java-service,
    datasource:
      url: jdbc:mysql://localhost:3306/clarityB2B2C,
    spring:
      datasource:
        username: root,
        password: root,
server:
  port: "8585"
  servlet:
    context-path: /api,
management:
  info:
   env:
    enabled: true,
  app:
    name: java-spring,
    developer: saravanan
developer:
    name: saravanan,
    profession: software-developer,

